### PR TITLE
[DO_NOT_MERGE] TEST: IGNORE

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero we can see what happens over here.

**Comment by gabemontero** [comment]
yep @bparees same error as with https://github.com/openshift/s2i-base/pull/96

**Comment by bparees** [comment]
K,  will look into it

**Comment by gabemontero** [comment]
@bparees see https://github.com/openshift/s2i-base/pull/96 ... got some triage and proposed solutions.

**Pull request closed without merging**
